<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title><?php echo(ucfirst($action)); ?></title>
    <link rel='stylesheet' href='styles/css/bootstrap.css'>
  </head>
  <body>
    <?php
	  include ('views/navigation.phtml');	
      include ('views/'.$template.'.phtml');
     ?>
     
  <script src='styles/js/jquery-3.1.1.min.js'></script>
  <script src='styles/js/bootstrap.js'></script>
  </body>
</html>
