<h1>Connexion</h1>
<?php
  if(isset($errors))
    foreach ($errors as $key => $value) {
      echo '<span style="color:red;"><b>Erreur : </b>'.$key.' : '.$value.'</span><br>';
    }
 ?>
<form action="index.php?action=doLogin" method="POST">
  Login : <input type="text" name="login" <?php if(isset($_POST['login'])){ echo 'value="'.$_POST['login'].'"'; }?>><br>
  Pass : <input type="password" name="password"><br>
  <input type="submit" value="Connexion">
</form>
