<h1>Inscription</h1>
<?php
$_SESSION['captcha'] = randomText();
  if(isset($errors))
    foreach ($errors as $key => $value) {
      echo '<span style="color:red;"><b>Erreur : </b>'.$key.' : '.$value.'</span><br>';
    }
 ?>
<form action="index.php?action=doSignup" method="POST">
  Login : <input type="text" name="login" <?php if(isset($_POST['login'])){ echo 'value="'.$_POST['login'].'"'; }?>><br>
  Pass : <input type="password" name="password"><br>
  Pass2 : <input type="password" name="password2"><br>
  Email : <input type="email" name="mail" <?php if(isset($_POST['mail'])){ echo 'value="'.$_POST['mail'].'"'; }?>><br>
  <img src="utilit/captcha.php"> Recopier le texte de l'image <br>
  <input type="text" name="captcha">
  <input type="submit" value="Inscription">
</form>